name: read-yaml

on:
  push:
  workflow_dispatch:

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: read-yaml-file
        uses: ndelangen/action-read-yaml@main
        id: read_action_js
        with:
          config: ${{ github.workspace }}/examples/basic/config_example_basic.yaml

      - name: use-yaml-file
        run: |
          echo namespace: ${{ steps.read_action_js.outputs['namespace'] }}
          echo location: ${{ steps.read_action_js.outputs['location'] }}
          echo environment: ${{ steps.read_action_js.outputs['environment'] }}
          echo resource_group_name: ${{ steps.read_action_js.outputs['resource_group_name'] }}
